### ISSUE TITLE
Parallelize mixed logit calculation and/or multistart runs for all models

### ISSUE THREAD

**Issue by crforsythe** [jhelvy/logitr#10]
For us to keep in mind - something I'll definitely be working on over the next month or so.

**Comment by jhelvy** [comment]
Consider? https://www.futureverse.org/

**Comment by jhelvy** [comment]
Changes in v0.2.6 have dramatically improved the estimation. Multi-start runs are quite fast now, even for mixed logit models, and thus parallelization may not really be needed. I'll leave this as a feature request but it won't be on the priority list for package improvements.

**Comment by jhelvy** [comment]
The multistart is now parallelized in v0.5.0. I haven't experimented yet with parallelizing the mixed logit calculation, but given the current computation speeds I doubt it will have a significant improvement.
