### ISSUE TITLE
Predicted names don't match

### ISSUE THREAD

**Issue by erikseulean** [jhelvy/logitr#41]
Hello, 

Thanks for providing the library, I found out about it a few days ago and it is truly amazing! 

I am trying to run a model that has one feature set as a factor, however it errors out when the factor levels in the `newdata` field provided to `predict` is different than the one provided in the train dataset.

I think the error comes from here: https://github.com/jhelvy/logitr/blob/e478e02d76903465d28197e9f0d343a68b7ae4bd/R/inputChecks.R#L156

In my case, the values provided in `newdata` are a subset of the ones provided in the train dataset. This case should be fine right, since no observation would have coefficients undetermined.

**Comment by jhelvy** [comment]
Hi, glad you're finding the package useful!

It is my understanding that the preferred  `predict()` method behavior is to require that `newdata` contain columns for all model parameters. 

This is true for other models as well. For example, using `lm()`, the `predict()` method will error unless you include all covariates in `newdata`. Here's a quick example:

```r
fit <- lm(mpg ~ hp + wt + disp, data = mtcars)
```

If I use `predict()` will all covariates, there's no error:
```r
pred <- predict(fit, mtcars[1:5, c('hp', 'wt', 'disp')])
```

Now if I use `predict()` where I've left out the "disp" covariate, I get the following error:

```r
pred <- predict(fit, mtcars[1:5, c('hp', 'wt')])
Error in eval(predvars, data, env) : object 'disp' not found
```

I think you have two options:

1. Estimate a model that only includes the covariates that are in your `newdata` (omit variables that are missing). This is probably less good as you could be introducing biases by leaving out important variables.
2. Include the missing variables in `newdata`. You can always make the values for those variables the same if they are not important in your prediction. For example, if you had some variables like `brand` that you didn't want to vary in your prediction, just set the `brand` variable in `newdata` to all be the same `brand`.

**Comment by jhelvy** [comment]
I can't reproduce this result. Here's an example using simulated data. 

I have another packaged called [{cbcTools}](https://github.com/jhelvy/cbcTools) that you can use to simulate choice-based conjoint survey data with.

```r
install.packages(c('logitr', 'remotes'))
remotes::install_github('jhelvy/cbcTools')
```

Use {cbcTools} to make a data set with random choices:

```r
library(cbcTools)
library(logitr)

profiles <- cbc_profiles(
    price     = seq(1, 4, 0.5), # $ per pound
    type      = c('Fuji', 'Gala', 'Honeycrisp'),
    freshness = c('Poor', 'Average', 'Excellent')
)

design <- cbc_design(
    profiles = profiles,
    n_resp   = 900, # Number of respondents
    n_alts   = 3,   # Number of alternatives per question
    n_q      = 6    # Number of questions per respondent
)

data <- cbc_choices(
    design,
    obsID = 'obsID'
)
```

Now estimate a logit model

```r
model <- logitr(
    data = data, 
    obsID = 'obsID', 
    outcome = 'choice',
    pars = c('price', 'type', 'freshness')
)
```

Make a new dataset where the `"Fuji"` level is not present for the `type` feature:

```r
new <- data
new[which(new$type == "Fuji"),]$type <- "Gala"
unique(new$type)

[1] Gala       Honeycrisp
Levels: Fuji Gala Honeycrisp
```

Make predictions using `model` and the `new` data:

```r
pred <- predict(
    object = model, 
    newdata = new, 
    obsID = "obsID", 
    returnData = TRUE
)
```

I get predicted probabilities without any errors.

**Comment by erikseulean** [comment]
> Make a new dataset where the `"Fuji"` level is not present for the `type` feature:
> 
> ```r
> new <- data
> new[which(new$type == "Fuji"),]$type <- "Gala"
> unique(new$type)
> 
> [1] Gala       Honeycrisp
> Levels: Fuji Gala Honeycrisp
> ```
> 
> Make predictions using `model` and the `new` data:
> 
> ```r
> pred <- predict(
>     object = model, 
>     newdata = new, 
>     obsID = "obsID", 
>     returnData = TRUE
> )
> ```
> 
> I get predicted probabilities without any errors.

I can actually reproduce the error with this case by doing the following:

```R
new$type = factor(c(rep("Gala", 8100), rep("Fuji", 8100)))
unique(new$type)
Gala Fuji
Levels:
'Fuji''Gala'
```
This is actually a valid example I think, if you read the data from a file, where it won't maintain the knowledge of the previous levels. In your situation, the levels are the one that are initially set, and you only change the values in the column.

**Comment by erikseulean** [comment]
So my workaround is doable, but incorrect. I'll actually check what `lm` does for this as I'm curious (but I'm fairly convinced it doesn't error out). From a user stand point it does not feel correct to have to supply all the factor levels, I feel that the error in the code is checking the wrong thing (I think it was rather intended to check the matching of the covariates rather than the levels). 

There are scenarios where the levels used to fit the model (present in the train) are not available to the user when the predict is called (one reason that I can think about is when the train data is huge and you want to dispose it from the memory after training, and the predictions are done at a way later point in time). 

The other logical question is why do you need to provide factor levels that you don't need ? The predictions can happen without these levels no ? 

Another scenario where this would fail is if you save your model to disk and then load it on a different machine where you don't have the data (which is somewhat common if you train and use on different clusters):

```R
saveRDS(mnl_pref, "model.rds")
my_model <- readRDS("model.rds")
```
Using it on the new cluster would have to ensure the levels, which is again incorrect in my opinion. 

From a correctness standpoint I could see two ways of doing this: 
1. The library would check that the factors in the test are a subset of the ones in the train
2. The library sets the factor levels based on the data that was trained on, and checks that no levels that was not trained on are present. 

In my situation I can go by adding the factor levels, however, 6 months down the line I can see how my predictions are based on some streamed input where I don't have access to the data anymore. 

Is there a library that you know that works on the principle mentioned above (where you have to alter the test data) as an example ? 

If you are willing to accept contributors to your library, and decide on a possible soultion, I am happy to get my hands dirty, read the code and send a PR.

**Comment by jhelvy** [comment]
I believe I may have fixed this issue on the latest branch. Can you try installing from that branch to test your data? 

```r
remotes::install_github("jhelvy/logitr@Rc-v1.0.0")
```

Here's an example using the `yogurt` data:

```r
library(logitr)

model <- logitr(
    data    = yogurt,
    outcome = 'choice',
    obsID   = 'obsID',
    pars    = c('price', 'feat', 'brand')
)
```

Use the model to make predictions using a subset of the original data:

```r
data <- subset(
    yogurt, obsID %in% c(42, 13),
    select = c('obsID', 'alt', 'price', 'feat', 'brand'))

probs <- predict(model, newdata = data, obsID = "obsID")
```

Now remove the 4th alternative from the data (eliminating the `"yoplait"` level from `brand`) and predict again:

```r
data2 <- data[which(data$alt != 4),]
probs <- predict(model, newdata = data2, obsID = "obsID")
```

No errors (hopefully)

**Comment by erikseulean** [comment]
Sorry for coming back so late. This seems to be working now! Thanks a lot for looking into it.
