### ISSUE TITLE
Compatibility with gtsummary v2.0

### ISSUE THREAD

**Issue by ddsjoberg** [jhelvy/logitr#56]
Dear @jhelvy , 

I am preparing the submission of gtsummary v2.0 to CRAN, and I wanted to alert you to a change you may need to incorporate in logitr.

The gtsummary package utilizes the broom.helpers package to prepare regression model results. In the updated version of the package, the broom.helpers package has moved from Imports to Suggests. As a result, you may also need to add broom.helpers to the logitr Suggests field so the package is available when your vignettes are created.

Apologies for any inconvenience, 
Daniel

**Comment by jhelvy** [comment]
Thanks for taking the time to make this check and make the adjustment for me! I'll merge the PR.

**Comment by jhelvy** [comment]
Btw, will this cause issues on CRAN? If so I can release a small update to CRAN.

**Comment by ddsjoberg** [comment]
> Btw, will this cause issues on CRAN? If so I can release a small update to CRAN.

I think you'll get an email from CRAN requiring an update once they get around to making the checks. FYI the CRAN holiday begins Aug 1: not sure what they're schedule is for the checks, however.

**Comment by jhelvy** [comment]
Already got an automated email from CRAN! Gonna push this version to get this taken care of.

**Comment by jhelvy** [comment]
Okay v1.1.2 is now up on CRAN with this fix, hopefully that solves everything.
